import React, { useEffect, useState } from "react";
import {
    getAllZones,
    addZone,
    updateZone,
    deleteZone,
} from "../../../services/informationService";

// Guidance for admin input fields
const FIELD_GUIDANCE = {
    ZoneID: "E.g. ZON_00001. Suggested: Autogenerated or unique.",
    ZoneName: "E.g. KLCC, Damansara, etc."
};

const TABLE_KEYS = [
    "ZoneID",
    "ZoneName"
];

const FIELD_LABELS = {
    ZoneID: "Zone ID",
    ZoneName: "Zone Name"
};

function Modal({ show, onClose, children }) {
    if (!show) return null;
    return (
        <div className="fixed inset-0 z-40 flex items-center justify-center bg-black bg-opacity-40">
            <div className="bg-white rounded-lg shadow-lg p-6 w-full max-w-lg relative max-h-[90vh] overflow-y-auto" tabIndex={-1}>
                <button onClick={onClose} className="absolute top-2 right-3 text-gray-400 hover:text-black text-lg" aria-label="Close">&times;</button>
                {children}
            </div>
        </div>
    );
}

export default function ZoneInfo() {
    const [zones, setZones] = useState([]);
    const [modalOpen, setModalOpen] = useState(false);
    const [modalMode, setModalMode] = useState("add"); // "add" or "edit"
    const [modalData, setModalData] = useState({});
    const [editIdx, setEditIdx] = useState(null);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [successMsg, setSuccessMsg] = useState("");
    const [error, setError] = useState(null);

    useEffect(() => { refreshZones(); }, []);
    async function refreshZones() {
        setLoading(true);
        try { setZones(await getAllZones()); } catch (e) { setError("Failed to fetch zones: " + e.message); }
        setLoading(false);
    }

    function openAddModal() {
        setModalMode("add");
        setModalData({
            ZoneID: "",
            ZoneName: ""
        });
        setModalOpen(true);
        setSuccessMsg(""); setError(null); setEditIdx(null);
    }

    function openEditModal(idx) {
        setModalMode("edit");
        setEditIdx(idx);
        setModalData({ ...zones[idx] });
        setModalOpen(true);
        setSuccessMsg(""); setError(null);
    }

    function handleModalChange(e) {
        const { name, value } = e.target;
        setModalData(prev => ({ ...prev, [name]: value }));
    }

    async function handleModalSubmit(e) {
        e.preventDefault();
        setSaving(true); setError(null); setSuccessMsg("");
        try {
            if (modalMode === "add") {
                const newZone = await addZone(modalData);
                setZones(prev => [...prev, newZone]);
                setSuccessMsg("Zone added!");
            } else {
                await updateZone(modalData.ZoneID, modalData);
                setZones(prev =>
                    prev.map((b, idx) => (idx === editIdx ? { ...modalData } : b))
                );
                setSuccessMsg("Zone updated!");
            }
            setModalOpen(false);
        } catch (e) {
            setError(modalMode === "add"
                ? "Failed to add zone: " + e.message
                : "Failed to update: " + e.message
            );
        }
        setSaving(false);
    }

    async function handleDelete(id) {
        if (!window.confirm("Delete this zone?")) return;
        setSaving(true); setError(null); setSuccessMsg("");
        try {
            await deleteZone(id);
            setZones(prev => prev.filter(t => (t.ZoneID || t.zone_id || t.id) !== id));
            setSuccessMsg("Zone deleted!");
        } catch (e) {
            setError("Failed to delete: " + e.message);
        }
        setSaving(false);
    }

    function renderInputField(k, val, onChange, isEdit) {
        // ZoneID is editable only on add, not on edit
        if (k === "ZoneID" && isEdit) {
            return (
                <input
                    name={k}
                    value={val ?? ""}
                    className="border p-2 rounded w-full text-sm bg-gray-100"
                    disabled
                />
            );
        }
        return (
            <input
                name={k}
                value={val ?? ""}
                onChange={onChange}
                className="border p-2 rounded w-full text-sm"
                required
                autoComplete="off"
            />
        );
    }
    function renderTableCell(k, val) {
        return <span className="text-xs">{val ?? "-"}</span>;
    }

    return (
        <div className="bg-white p-3 rounded shadow">
            <div className="flex justify-end mb-4">
                <button onClick={openAddModal} className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 text-xs">+ Add Zone</button>
            </div>
            {successMsg && <div className="mb-4 text-green-600 text-xs">{successMsg}</div>}
            {error && <div className="mb-4 text-red-600 text-xs">{error}</div>}
            <div className="overflow-x-auto">
                <table className="min-w-full border border-gray-200 rounded bg-white">
                    <thead className="bg-gray-100">
                        <tr>
                            <th className="p-2 border text-xs">#</th>
                            {TABLE_KEYS.map(k => <th key={k} className="p-2 border text-xs">{FIELD_LABELS[k] || k}</th>)}
                            <th className="p-2 border text-xs">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {loading ? (
                            <tr><td colSpan={TABLE_KEYS.length + 2} className="text-center p-6 text-xs">Loading...</td></tr>
                        ) : zones.length === 0 ? (
                            <tr><td colSpan={TABLE_KEYS.length + 2} className="text-center py-6 text-xs">No zones found.</td></tr>
                        ) : (
                            zones.map((item, idx) => (
                                <tr key={item.ZoneID || item.zone_id || item.id}>
                                    <td className="p-2 border text-center font-mono text-xs">{idx + 1}</td>
                                    {TABLE_KEYS.map(k => (
                                        <td className="p-2 border text-xs" key={k}>
                                            {renderTableCell(k, item[k])}
                                        </td>
                                    ))}
                                    <td className="p-2 border text-xs">
                                        <div className="flex gap-2">
                                            <button
                                                onClick={() => openEditModal(idx)}
                                                className="px-2 py-1 rounded hover:bg-blue-100 text-blue-600 text-lg"
                                                title="Edit"
                                                disabled={saving}
                                                aria-label="Edit"
                                            >
                                                ✏️
                                            </button>
                                            <button
                                                onClick={() => handleDelete(item.ZoneID || item.zone_id || item.id)}
                                                className="px-2 py-1 rounded hover:bg-red-100 text-red-600 text-lg"
                                                title="Delete"
                                                disabled={saving}
                                                aria-label="Delete"
                                            >
                                                🗑️
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
            {/* Add/Edit Modal */}
            <Modal show={modalOpen} onClose={() => setModalOpen(false)}>
                <h3 className="text-xl font-semibold mb-4">
                    {modalMode === "add" ? "Add New Zone" : "Edit Zone"}
                </h3>
                <form onSubmit={handleModalSubmit} className="space-y-3">
                    {TABLE_KEYS.map(k => (
                        <div key={k}>
                            <label className="block font-medium mb-1 text-sm">{FIELD_LABELS[k] || k}</label>
                            {renderInputField(k, modalData[k], handleModalChange, modalMode === "edit")}
                            {FIELD_GUIDANCE[k] && (<div className="text-xs text-gray-400 mt-1">{FIELD_GUIDANCE[k]}</div>)}
                        </div>
                    ))}
                    <div className="flex gap-3 pt-2">
                        <button
                            type="submit"
                            className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 text-xs"
                            disabled={saving}
                        >
                            {saving
                                ? (modalMode === "add" ? "Adding..." : "Saving...")
                                : (modalMode === "add" ? "Add Zone" : "Save")}
                        </button>
                        <button
                            type="button"
                            onClick={() => setModalOpen(false)}
                            className="bg-gray-300 px-4 py-2 rounded hover:bg-gray-400 text-xs"
                            disabled={saving}
                        >
                            Cancel
                        </button>
                    </div>
                </form>
            </Modal>
        </div>
    );
}